### ISSUE TITLE
Link to package download

### ISSUE THREAD

**Issue by pdwaggoner** [rsquaredacademy/vistributions#19]
Hi - thanks for this great tool! I really enjoyed it. You may want to consider linking to either your github repo or CRAN for direct download from the web version of the tool, e.g., `https://cran.r-project.org/web/packages/vistributions/index.html` . Just a thought as some students may want to inspect the source files or download it after interacting with the web version. Either way, thanks!

**Comment by aravindhebbali** [comment]
Yes.. I had completely forgotten to add links in the app. Thanks for the suggestion @pdwaggoner
